# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 21:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anger', models.FloatField()),
                ('contempt', models.FloatField()),
                ('disgust', models.FloatField()),
                ('fear', models.FloatField()),
                ('happiness', models.FloatField()),
                ('neutral', models.FloatField()),
                ('sadness', models.FloatField()),
                ('surprise', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
