# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_emotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='date_recorded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
