# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import emotion_authentication.face_verification


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceVerificationManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_face', models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, emotion_authentication.face_verification.FaceVerification),
        ),
    ]
