# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceverificationmanager',
            name='auth_face',
            field=models.ImageField(blank=True, null=True, upload_to='auth_faces'),
        ),
    ]
