# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_authentication', '0002_auto_20171221_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceverificationmanager',
            name='auth_face_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='faceverificationmanager',
            name='auth_last_recorded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
