# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionprofile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
